/*
What if a callback has a callback? While doing multiple asynchronous operations, the callback get nested to each other which leads to callback hell.
Callback function can not be chained together which leads to nested callback while calling it multiple time which leads to callback hell.
To overcome the problem of callback hell, we use promise which we will see next.
*/